# Generated by Django 5.1.3 on 2024-12-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_content', '0002_alter_course_slug_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
