# Generated by Django 5.1.3 on 2024-12-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_content', '0004_course_technologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='technologies',
        ),
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.ManyToManyField(related_name='courses', to='portfolio_content.technology'),
        ),
    ]
