# Generated by Django 5.1.3 on 2024-12-26 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_content', '0007_submission'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='technology',
            table='Technologies',
        ),
    ]
