# Generated by Django 5.1.3 on 2024-12-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_content', '0008_alter_technology_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technologies'},
        ),
    ]
