# Generated by Django 5.1.3 on 2024-12-27 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_content', '0009_alter_technology_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
