# Generated by Django 5.1.3 on 2024-12-27 02:18

import django.db.models.deletion
from django.db import migrations, models


def create_default_problem_set(apps, schema_editor):
    # Get the models
    Course = apps.get_model('portfolio_content', 'Course')
    ProblemSet = apps.get_model('portfolio_content', 'ProblemSet')

    # Create a default course if none exists
    default_course, _ = Course.objects.get_or_create(
        name='Default Course',
        description='Placeholder course for default problem sets.',
    )

    # Create a default problem set
    default_problem_set, _ = ProblemSet.objects.get_or_create(
        title='Default Problem Set',
        description='Placeholder problem set for submissions.',
        course=default_course,
    )

    # Set the default ID to use in submissions
    schema_editor.execute(
        f"UPDATE portfolio_content_submission SET problem_set_id = {default_problem_set.id} WHERE problem_set_id IS NULL"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_content', '0010_remove_submission_project_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='portfolio_content.course')),
                ('technologies', models.ManyToManyField(related_name='labs', to='portfolio_content.technology')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='portfolio_content.lab'),
        ),
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_link', models.URLField(blank=True)),
                ('screenshot_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_sets', to='portfolio_content.course')),
                ('technologies', models.ManyToManyField(related_name='problem_sets', to='portfolio_content.technology')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='problem_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='portfolio_content.problemset'),
        ),
        migrations.RunPython(create_default_problem_set),
    ]
