# Generated by Django 5.1.3 on 2024-12-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_content', '0011_lab_submission_lab_problemset_submission_problem_set'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemset',
            options={'verbose_name_plural': 'Problem Sets'},
        ),
    ]
