# Generated by Django 5.1.3 on 2024-12-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_content', '0012_alter_problemset_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemset',
            name='project_link',
        ),
        migrations.RemoveField(
            model_name='problemset',
            name='screenshot_url',
        ),
    ]
