# Generated by Django 5.1.3 on 2024-12-27 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_content', '0013_remove_problemset_project_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='problem_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='portfolio_content.problemset'),
        ),
    ]
