# Generated by Django 5.1.3 on 2024-12-27 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_content', '0014_alter_submission_problem_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('screenshot_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_projects', to='portfolio_content.course')),
                ('technologies', models.ManyToManyField(related_name='final_projects', to='portfolio_content.technology')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='final_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='portfolio_content.finalproject'),
        ),
    ]
