# Generated by Django 5.1.3 on 2024-12-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_content', '0015_finalproject_submission_final_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalproject',
            options={'verbose_name_plural': 'Final Project'},
        ),
        migrations.AddField(
            model_name='finalproject',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
