# Generated by Django 5.1.3 on 2024-12-29 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_content', '0016_alter_finalproject_options_finalproject_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio_content.course')),
                ('technologies', models.ManyToManyField(related_name='projects', to='portfolio_content.technology')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
